# Programa Ingenias+ Data Science

Como dijimos en clases anteriores, Python tiene implementadas muchas librerias para poder trabajar con datos. En la clase de hoy trabajaremos con una de ellas: `Numpy`.

Antes de comenzar, vamos a hablar un poco de esta libreria o modulo.

**Numpy** es una librería optimizada para realizar cálculos numéricos con vectores y matrices. A diferencia de otros lenguajes de programación, Python no posee en su estructura central la figura de matrices. Eso quiere decir que para poder trabajar con esta estructura de datos deberiamos trabajar con listas de listas. NumPy introduce el concepto de arrays o matrices.

Al ser de código abierto, `numpy` posee una documentación muy amplia que es **SIEMPRE RECOMENDABLE** consultar.

- [Documentacion NumPy](https://devdocs.io/numpy/)

## Clase 4: Introduccion a NumPy

# Ejercicios

1. Crear un arreglo de ceros de longitud 12
2. Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
3. Crear un arreglo que tenga los números del 10 al 49
4. Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
5. Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
6. Calcular la media de un arreglo usando np.sum
7. Calcular la varianza de un arreglo usando np.sum y np.mean
8. Crear un array de números aleatorios usando np.random.randn.


In [ ]:
# Importamos la biblioteca Numpy
import numpy as np

In [ ]:
# Ejericio 1
# Crear un arreglo de ceros de longitud 12
array_1 = np.zeros(12)
print(array_1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
# Ejercicio 2
# Crea un arrelgo de longitud 10 con ceros en todas las posiciones y un 10 en la posicion numero 5
array_2 = np.zeros(10)
array_2[4] = 10
print(array_2)


[ 0.  0.  0.  0. 10.  0.  0.  0.  0.  0.]


In [ ]:
# Ejercicio 3
# Crear un arreglo que tenga los números del 10 al 49

array_3 = np.arange(10,50)
print(array_3)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
# Ejercicio 4
# Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
array_4 = np.arange(9).reshape(3,3)
print(array_4)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
# Ejercicio 5
# Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza.
array_5 = np.random.randn(100)
media_array_5 = np.mean(array_5) #media
var_array_5 = np.var(array_5) #varianza
print('la media del arreglo es', media_array_5, 'y la varianza', var_array_5)

creacion de longuitud aleatorio de 100 
la media del arreglo es -0.03814837027682873 y la varianza 1.0086167111534527


In [ ]:
# Ejericio 6
# Calcular la media de un arreglo usando np.sum
media = np.sum(array_5)/len(array_5)
#en este caso utilizo el array anterior para calcularlo, pero vale para cualquier arreglo de cualquier
#longitud
print(media)


-0.03814837027682873


In [ ]:
# Ejercicio7
# Calcular la varianza de un arreglo usando np.sum y np.mean
varianza = np.sum((array_5-np.mean(array_5))**2)/len(array_5)
print(varianza)


1.0086167111534527


In [ ]:
# Ejercicio 8
# Crear un array de números aleatorios usando np.random.randn
array_8 = np.random.randn(10)
print(array_8)


[ 0.32687236  0.89546275  1.11039834  0.58703419  1.97151532 -0.18441855
 -0.66004564  0.62679253 -0.1556949   0.8859229 ]
